# Alle hier gesetzten Werte können über `$addon->getProperty($key)` abgefragt werden

package: watch_list
version: '1.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/watch_list

requires:
    php:
        extensions: [session]
